"""Seed transcripts and jargon glossary for the mock vector store."""

from datetime import UTC, datetime, timedelta

from pitwallai.agents.radio_intercept.enums import RadioIntent, StrategicSignal
from pitwallai.agents.radio_intercept.models import RadioRawMessage, RehearsalScenario

SEED_TRANSCRIPTS: list[dict] = [
    {
        "doc_id": "seed-001",
        "raw_transcript": "Box, box, box. Pit confirm.",
        "decoded_intent": RadioIntent.PIT_CALL.value,
        "strategic_signal": StrategicSignal.IMMINENT_PIT_WINDOW.value,
        "session_type": "race",
        "lap_number": 18,
        "outcome": "Driver pitted lap 19, undercut on rival",
        "team": "Red Bull Racing",
        "driver_code": "VER",
    },
    {
        "doc_id": "seed-002",
        "raw_transcript": "Tyres are gone, mate. Front left is dead.",
        "decoded_intent": RadioIntent.TIRE_COMPLAINT.value,
        "strategic_signal": StrategicSignal.TIRE_DEGRADATION_HIGH.value,
        "session_type": "race",
        "lap_number": 32,
        "outcome": "Pit lap 33, switched to hards",
        "team": "Mercedes",
        "driver_code": "HAM",
    },
    {
        "doc_id": "seed-003",
        "raw_transcript": "Push, push, push. Maximum attack now.",
        "decoded_intent": RadioIntent.PUSH_MODE.value,
        "strategic_signal": StrategicSignal.PACE_MODE_SHIFT.value,
        "session_type": "race",
        "lap_number": 41,
        "outcome": "Driver closed 1.2s gap in 4 laps",
        "team": "McLaren",
        "driver_code": "NOR",
    },
    {
        "doc_id": "seed-004",
        "raw_transcript": "Copy that, stay out. Extend to lap 28.",
        "decoded_intent": RadioIntent.CONSERVE_MODE.value,
        "strategic_signal": StrategicSignal.OVERCUT_ATTEMPT.value,
        "session_type": "race",
        "lap_number": 22,
        "outcome": "Overcut successful, gained one position",
        "team": "Ferrari",
        "driver_code": "LEC",
    },
    {
        "doc_id": "seed-005",
        "raw_transcript": "We need to talk about engine modes. Switch to mode 3.",
        "decoded_intent": RadioIntent.ENGINE_MODE_CHANGE.value,
        "strategic_signal": StrategicSignal.PACE_MODE_SHIFT.value,
        "session_type": "race",
        "lap_number": 15,
        "outcome": "Lap time improved 0.3s per lap",
        "team": "Ferrari",
        "driver_code": "SAI",
    },
    {
        "doc_id": "seed-006",
        "raw_transcript": "Safety car is out. Box this lap, box this lap.",
        "decoded_intent": RadioIntent.SAFETY_CAR_RESPONSE.value,
        "strategic_signal": StrategicSignal.SAFETY_CAR_STRATEGY.value,
        "session_type": "race",
        "lap_number": 47,
        "outcome": "Free pit stop, retained P3",
        "team": "Mercedes",
        "driver_code": "RUS",
    },
    {
        "doc_id": "seed-007",
        "raw_transcript": "What's the weather doing at turn three? Looks like spots.",
        "decoded_intent": RadioIntent.WEATHER_QUERY.value,
        "strategic_signal": StrategicSignal.NEUTRAL.value,
        "session_type": "race",
        "lap_number": 29,
        "outcome": "Stayed on slicks, light drizzle passed",
        "team": "Red Bull Racing",
        "driver_code": "VER",
    },
    {
        "doc_id": "seed-008",
        "raw_transcript": "Something feels wrong with the rear. Big snap in turn six.",
        "decoded_intent": RadioIntent.MECHANICAL_ISSUE.value,
        "strategic_signal": StrategicSignal.RELIABILITY_RISK.value,
        "session_type": "race",
        "lap_number": 36,
        "outcome": "Retired lap 38, rear suspension failure",
        "team": "Alpine",
        "driver_code": "OCO",
    },
    {
        "doc_id": "seed-009",
        "raw_transcript": "Gap is 2.3 and closing. What's the interval behind?",
        "decoded_intent": RadioIntent.GAP_UPDATE_REQUEST.value,
        "strategic_signal": StrategicSignal.NEUTRAL.value,
        "session_type": "race",
        "lap_number": 24,
        "outcome": "Maintained position, gap stabilized at 2.1s",
        "team": "McLaren",
        "driver_code": "NOR",
    },
    {
        "doc_id": "seed-010",
        "raw_transcript": "This is ridiculous. I have no grip at all.",
        "decoded_intent": RadioIntent.DRIVER_FRUSTRATION.value,
        "strategic_signal": StrategicSignal.TIRE_DEGRADATION_HIGH.value,
        "session_type": "race",
        "lap_number": 44,
        "outcome": "Pit called next lap",
        "team": "Mercedes",
        "driver_code": "HAM",
    },
    {
        "doc_id": "seed-011",
        "raw_transcript": "Fuel saving mode on. Lift and coast into turn one.",
        "decoded_intent": RadioIntent.FUEL_MANAGEMENT.value,
        "strategic_signal": StrategicSignal.NEUTRAL.value,
        "session_type": "race",
        "lap_number": 52,
        "outcome": "Finished race without fuel penalty",
        "team": "Aston Martin",
        "driver_code": "ALO",
    },
    {
        "doc_id": "seed-012",
        "raw_transcript": "DRS is not opening. I've tried the flap twice.",
        "decoded_intent": RadioIntent.DRS_ISSUE.value,
        "strategic_signal": StrategicSignal.RELIABILITY_RISK.value,
        "session_type": "race",
        "lap_number": 11,
        "outcome": "Pit lap 12 for DRS actuator check, lost 25s",
        "team": "Williams",
        "driver_code": "ALB",
    },
    {
        "doc_id": "seed-013",
        "raw_transcript": "Multi 21. Multi 21. Confirm.",
        "decoded_intent": RadioIntent.PIT_CALL.value,
        "strategic_signal": StrategicSignal.IMMINENT_PIT_WINDOW.value,
        "session_type": "race",
        "lap_number": 27,
        "outcome": "Pit stop 2.4s, emerged ahead of PER",
        "team": "Red Bull Racing",
        "driver_code": "VER",
    },
    {
        "doc_id": "seed-014",
        "raw_transcript": "Negative, negative. Stay out. We are going long.",
        "decoded_intent": RadioIntent.CONSERVE_MODE.value,
        "strategic_signal": StrategicSignal.OVERCUT_ATTEMPT.value,
        "session_type": "race",
        "lap_number": 19,
        "outcome": "One-stop strategy completed, P4 finish",
        "team": "Ferrari",
        "driver_code": "LEC",
    },
    {
        "doc_id": "seed-015",
        "raw_transcript": "VSC is deployed. No overtaking, keep delta positive.",
        "decoded_intent": RadioIntent.SAFETY_CAR_RESPONSE.value,
        "strategic_signal": StrategicSignal.SAFETY_CAR_STRATEGY.value,
        "session_type": "race",
        "lap_number": 33,
        "outcome": "Stayed out, gained track position",
        "team": "McLaren",
        "driver_code": "NOR",
    },
    {
        "doc_id": "seed-016",
        "raw_transcript": "Rear is overheating. Manage temps, short shift.",
        "decoded_intent": RadioIntent.MECHANICAL_ISSUE.value,
        "strategic_signal": StrategicSignal.RELIABILITY_RISK.value,
        "session_type": "race",
        "lap_number": 48,
        "outcome": "Reduced pace 3 laps, temps normalized",
        "team": "Mercedes",
        "driver_code": "RUS",
    },
    {
        "doc_id": "seed-017",
        "raw_transcript": "Deploy full ERS. We need one more lap of push.",
        "decoded_intent": RadioIntent.PUSH_MODE.value,
        "strategic_signal": StrategicSignal.UNDERCUT_OPPORTUNITY.value,
        "session_type": "race",
        "lap_number": 16,
        "outcome": "Undercut successful, jumped to P2",
        "team": "Ferrari",
        "driver_code": "SAI",
    },
    {
        "doc_id": "seed-018",
        "raw_transcript": "What's our delta to the car ahead on fresh tyres?",
        "decoded_intent": RadioIntent.GAP_UPDATE_REQUEST.value,
        "strategic_signal": StrategicSignal.UNDERCUT_OPPORTUNITY.value,
        "session_type": "qualifying",
        "lap_number": None,
        "outcome": "Proceeded with out-lap, Q3 reached",
        "team": "Red Bull Racing",
        "driver_code": "VER",
    },
    {
        "doc_id": "seed-019",
        "raw_transcript": "Graining on the rears. I cannot push.",
        "decoded_intent": RadioIntent.TIRE_COMPLAINT.value,
        "strategic_signal": StrategicSignal.TIRE_DEGRADATION_HIGH.value,
        "session_type": "race",
        "lap_number": 38,
        "outcome": "Boxed for mediums, undercut failed",
        "team": "Mercedes",
        "driver_code": "HAM",
    },
    {
        "doc_id": "seed-020",
        "raw_transcript": "Harvest in sector two, deploy in sector three.",
        "decoded_intent": RadioIntent.ENGINE_MODE_CHANGE.value,
        "strategic_signal": StrategicSignal.PACE_MODE_SHIFT.value,
        "session_type": "race",
        "lap_number": 7,
        "outcome": "Maintained P5 through first stint",
        "team": "McLaren",
        "driver_code": "NOR",
    },
    {
        "doc_id": "seed-021",
        "raw_transcript": "Box for hards. Hard tyres. Pit this lap.",
        "decoded_intent": RadioIntent.PIT_CALL.value,
        "strategic_signal": StrategicSignal.IMMINENT_PIT_WINDOW.value,
        "session_type": "race",
        "lap_number": 31,
        "outcome": "Pit 2.6s, rejoined in clean air",
        "team": "Aston Martin",
        "driver_code": "ALO",
    },
    {
        "doc_id": "seed-022",
        "raw_transcript": "Dirty air is killing me. I need clean air now.",
        "decoded_intent": RadioIntent.DRIVER_FRUSTRATION.value,
        "strategic_signal": StrategicSignal.PACE_MODE_SHIFT.value,
        "session_type": "race",
        "lap_number": 26,
        "outcome": "Pit undercut attempted lap 27",
        "team": "Ferrari",
        "driver_code": "LEC",
    },
]

JARGON_GLOSSARY: dict[str, str] = {
    "box": "Pit entry instruction — come into the pits immediately",
    "multi-21": "Coded pit-entry confirmation (team-specific)",
    "multi 21": "Coded pit-entry confirmation (team-specific)",
    "delta": "Time gap to a reference car (ahead or behind)",
    "undercut": "Pit early to gain track position when rival pits later on worn tyres",
    "overcut": "Stay out longer than rival to gain position on fresher tyres",
    "drs": "Drag Reduction System — rear wing flap for straight-line speed",
    "vsc": "Virtual Safety Car — reduced speed delta, no overtaking",
    "sc": "Full Safety Car — pace car leads field, pit window opportunity",
    "gap": "Time or distance to car ahead",
    "interval": "Time gap to the car directly behind",
    "ers": "Energy Recovery System — electrical power deployment and harvesting",
    "mgu-k": "Motor Generator Unit — Kinetic (brake energy recovery)",
    "mgu-h": "Motor Generator Unit — Heat (turbo energy recovery)",
    "deploy": "Release stored electrical energy for acceleration",
    "harvest": "Recover electrical energy under braking or off-throttle",
    "lift-and-coast": "Coast before braking to save fuel and manage temperatures",
    "lift and coast": "Coast before braking to save fuel and manage temperatures",
    "mode": "Engine or power-unit operating mode (affects performance and reliability)",
    "stint": "Continuous run on a single set of tyres before pitting",
    "window": "Optimal lap range to execute a pit stop strategically",
    "marbles": "Rubber debris off the racing line that reduces grip",
    "graining": "Tyre surface tearing causing reduced grip and overheating",
    "blistering": "Tyre internal heat causing tread chunks to detach",
    "flat-spot": "Localized tyre wear from locked wheel causing vibration",
    "flat spot": "Localized tyre wear from locked wheel causing vibration",
    "snap": "Sudden oversteer breakaway at the rear axle",
    "oversteer": "Rear of car slides more than front — unstable handling",
    "understeer": "Front of car slides less than rear — won't turn in",
    "wake": "Turbulent airflow behind a leading car",
    "dirty air": "Disrupted airflow from car ahead reducing downforce and grip",
    "tow": "Aerodynamic slipstream benefit from car ahead",
    "offset strategy": "Pit on a different lap than rivals to gain track position",
    "push": "Maximum pace — extract all available performance",
    "stay out": "Do not pit — continue on current tyres",
    "tyres": "Pirelli compound fitted to the car",
    "hards": "Hard compound tyre — durable, lower peak grip",
    "mediums": "Medium compound tyre — balance of pace and durability",
    "softs": "Soft compound tyre — peak grip, rapid degradation",
    "copy": "Message acknowledged and understood",
    "negative": "Instruction rejected — do not perform the action",
    "fuel saving": "Reduce fuel consumption via lift-and-coast and short shifts",
    "pit confirm": "Driver confirms pit entry instruction received",
}

TEAM_COLORS: dict[str, str] = {
    "McLaren": "#FF8000",
    "Red Bull Racing": "#3671C6",
    "Ferrari": "#E8002D",
    "Mercedes": "#27F4D2",
    "Aston Martin": "#229971",
    "Alpine": "#0093CC",
    "Williams": "#64C4FF",
    "Haas": "#B6BABD",
    "Sauber": "#52E252",
    "RB": "#6692FF",
}

DRIVER_CONTEXT: dict[str, dict] = {
    "VER": {
        "name": "Max Verstappen",
        "team": "Red Bull Racing",
        "number": 1,
        "communication_style": "Terse and technical; minimal small talk",
        "known_phrases": ["box box box", "multi 21", "push now", "no mate"],
        "strategy_tendency": "Aggressive undercut preference; late-brake defensive driving",
    },
    "HAM": {
        "name": "Lewis Hamilton",
        "team": "Mercedes",
        "number": 44,
        "communication_style": "Expressive; detailed tyre and balance feedback",
        "known_phrases": ["tyres are gone", "no grip", "bouncing", "need more front"],
        "strategy_tendency": "Flexible on strategy; strong tyre management in stint extension",
    },
    "NOR": {
        "name": "Lando Norris",
        "team": "McLaren",
        "number": 4,
        "communication_style": "Conversational but precise on car balance",
        "known_phrases": ["dirty air", "snap", "deploy", "stay out"],
        "strategy_tendency": "Track-position aware; prefers clean-air offset strategy",
    },
    "PIA": {
        "name": "Oscar Piastri",
        "team": "McLaren",
        "number": 81,
        "communication_style": "Calm and methodical; mirrors engineer cadence",
        "known_phrases": ["copy", "stay out", "gap is", "box box"],
        "strategy_tendency": "Consistent tyre management; undercut when track position allows",
    },
    "LEC": {
        "name": "Charles Leclerc",
        "team": "Ferrari",
        "number": 16,
        "communication_style": "Direct; quick gap and delta requests",
        "known_phrases": ["negative negative", "stay out", "gap is", "oversteer"],
        "strategy_tendency": "Overcut-friendly on softer compounds; aggressive on quali pace",
    },
    "SAI": {
        "name": "Carlos Sainz",
        "team": "Ferrari",
        "number": 55,
        "communication_style": "Methodical and calm; thorough on tyre state",
        "known_phrases": ["engine mode", "harvest", "understeer", "box for hards"],
        "strategy_tendency": "Consistent one-stop bias; strong race-pace tyre warmup",
    },
    "RUS": {
        "name": "George Russell",
        "team": "Mercedes",
        "number": 63,
        "communication_style": "Technical and measured; precise on gaps",
        "known_phrases": ["delta", "interval", "fuel saving", "manage temps"],
        "strategy_tendency": "Conservative early stint; strong safety-car reaction",
    },
    "ANT": {
        "name": "Andrea Kimi Antonelli",
        "team": "Mercedes",
        "number": 12,
        "communication_style": "Brief and coachable; defers to engineer prompts",
        "known_phrases": ["copy", "gap", "push", "tyres"],
        "strategy_tendency": "Follows team race plan; conservative in Monaco traffic",
    },
    "ALO": {
        "name": "Fernando Alonso",
        "team": "Aston Martin",
        "number": 14,
        "communication_style": "Experienced; strategic questioning on rival moves",
        "known_phrases": ["stay out", "window", "undercut", "marbles"],
        "strategy_tendency": "Opportunistic pit windows; strong in mixed conditions",
    },
    "STR": {
        "name": "Lance Stroll",
        "team": "Aston Martin",
        "number": 18,
        "communication_style": "Direct feedback on balance; shorter transmissions",
        "known_phrases": ["no grip", "snap", "box", "copy"],
        "strategy_tendency": "Early pit when tyres fade; track-position defensive",
    },
}

_MONACO_SESSION_KEY = 9158
_MONACO_BASE = datetime(2024, 5, 26, 14, 35, 0, tzinfo=UTC)


def _monaco_event(
    offset_seconds: float,
    lap: int,
    driver_number: int,
    driver_code: str,
    team: str,
    transcript: str,
) -> RadioRawMessage:
    """Build a single Monaco rehearsal radio event."""
    return RadioRawMessage(
        session_key=_MONACO_SESSION_KEY,
        driver_number=driver_number,
        driver_code=driver_code,
        team=team,
        timestamp=_MONACO_BASE + timedelta(seconds=offset_seconds),
        raw_transcript=transcript,
        recording_url=None,
        lap_number=lap,
    )


MONACO_REHEARSAL_SCENARIO = RehearsalScenario(
    name="monaco_2024",
    circuit="Circuit de Monaco",
    year=2024,
    description=(
        "Late-race Monaco 2024 strategic arc: McLaren manages Ferrari undercut pressure "
        "while Norris fights critical rear tyre degradation before the pit resolution."
    ),
    events=[
        _monaco_event(0, 34, 1, "VER", "Red Bull Racing", "Max, gap to Lando is 2.8 and stable. Tyre delta is plus 0.4 in your favour."),
        _monaco_event(52, 35, 16, "LEC", "Ferrari", "Charles, front left is graining heavily. Sector two is getting worse. We need to talk about the window."),
        _monaco_event(108, 35, 4, "NOR", "McLaren", "What's the gap to Verstappen? And what are Ferrari doing?"),
        _monaco_event(165, 36, 4, "NOR", "McLaren", "Copy. We're managing. Tyres feel okay. Just need the gap."),
        _monaco_event(220, 36, 16, "LEC", "Ferrari", "Box this lap? What's the gap to traffic? I'm ready if you say so."),
        _monaco_event(258, 37, 16, "LEC", "Ferrari", "Box box box."),
        _monaco_event(310, 37, 1, "VER", "Red Bull Racing", "Understood. Ferrari is in. What do we do? Do we cover or go long?"),
        _monaco_event(355, 38, 81, "PIA", "McLaren", "Tyres are okay here. Rears are warm. I can push if you need."),
        _monaco_event(
            398,
            38,
            4,
            "NOR",
            "McLaren",
            "These tyres are gone, mate. Fronts are completely dead. I've got nothing through the chicane. You need to box me, I can't hold this.",
        ),
        _monaco_event(441, 39, 4, "NOR", "McLaren", "Box box box. Understood."),
        _monaco_event(482, 39, 4, "NOR", "McLaren", "Okay. New tyres feel good. What's the gap to Leclerc? Can we make this work?"),
        _monaco_event(534, 40, 4, "NOR", "McLaren", "Copy 3.1 seconds. Push push push. Let's go."),
    ],
)
